#!/usr/bin/env python

import sys
import subprocess
import os


pathProc = subprocess.Popen( [ "../src/saru-path-helper", "find-root", "../fakeproject/subdir" ], stdout=subprocess.PIPE, stderr=subprocess.PIPE )
retcode = pathProc.wait()

if( retcode != 0 ) :
  exit(1)

com = pathProc.communicate()[0]
lines = com.splitlines()
if ( len(lines)!= 1 ):
  exit(1)
if ( lines[0] != "/Users/michaelanderson/Code/git/saru/fakeproject"):
  exit(1)
exit(0)
