#!/usr/bin/env python

import sys
import subprocess
import os


pathProc = subprocess.Popen( [ "../src/saru-path-helper", "find-root", "../fakeproject/subdir" ], stdout=subprocess.PIPE, stderr=subprocess.PIPE )
retcode = pathProc.wait()

if( retcode != 0 ) :
  print >> sys.stderr, "returned non-zero exit code"
  exit(1)

(procstdout, procstderr) = pathProc.communicate()

lines = procstderr.splitlines()
if ( len(lines)!= 0 ):
  print >> sys.stderr, "Non-empty stderr"
  print >> sys.stderr, procstderr
  exit(1)

lines = procstdout.splitlines()
if ( len(lines)!= 1 ):
  print >> sys.stderr, "Wrong number of stdout lines"
  print >> sys.stderr, procstdout
  exit(1)
if ( lines[0] != "/Users/michaelanderson/Code/git/saru/fakeproject"):
  print >> sys.stderr, "Line of stdout not as expected"
  print >> sys.stderr, procstdout
  exit(1)
exit(0)
