#!/usr/bin/env python

import sys
import subprocess
import os


pathProc = subprocess.Popen( [ "../src/saru-path-helper", "find-root", "../fakeproject/notsubdir" ], stdout=subprocess.PIPE, stderr=subprocess.PIPE )
retcode = pathProc.wait()

if (retcode == 0 ) :
  exit(1)

(procstdout, procstderr) = pathProc.communicate()
lines=procstdout.splitlines()
if(len(lines)!=0):
  exit(1)
lines=procstderr.splitlines()
if(len(lines)!=1):
  exit(1)
if( lines[0].strip() != "saru-path-helper : find-root expects a directory argument" ):
  exit(1)
exit(0)
