#!/usr/bin/env python

import sys
import subprocess
import os


runProc = subprocess.Popen( [ "../src/saru-run-test","single", "../fakeproject/passingtest.bash" ], stdout=subprocess.PIPE, stderr=subprocess.PIPE )
retcode = runProc.wait()

if( retcode != 0 ) :
  print >> sys.stderr, "returned non-zero exit code"
  exit(1)

(procstdout, procstderr) = runProc.communicate()

lines = procstderr.splitlines()
if ( len(lines)!= 0 ):
  print >> sys.stderr, "Non-empty stderr"
  print >> sys.stderr, procstderr
  exit(1)

lines = procstdout.splitlines()
if ( len(lines)!= 1 ):
  print >> sys.stderr, "Wrong number of stdout lines"
  print >> sys.stderr, procstdout
  exit(1)
if ( lines[0] != "OK"):
  print >> sys.stderr, "Line of stdout not \"OK\""
  print >> sys.stderr, procstdout
  exit(1)
exit(0)
