#!/usr/bin/env python

import sys
import subprocess
import os
import difflib


runProc = subprocess.Popen( [ "../src/saru-run-test","single", "fakeproject/nonexistanttest.bash" ], stdout=subprocess.PIPE, stderr=subprocess.PIPE )
retcode = runProc.wait()

if( retcode != 1 ) :
  print >> sys.stderr, "returned non-one exit code"
  (procstdout, procstderr) = runProc.communicate()
  print >> sys.stderr, procstderr
  print >> sys.stderr, procstdout
  exit(1)

(procstdout, procstderr) = runProc.communicate()

expectedOutput="""nonexistanttest.bash : FAILED
==MESSAGE==
saru-run-test : nonexistant test nonexistanttest.bash


0 / 1 [ 0 skipped ]
"""

expectedError=""

OK=True
if ( procstdout!= expectedOutput ):
  print >> sys.stderr, "output not as expected"
  print >> sys.stderr, "EXPECTED:"
  print >> sys.stderr, expectedOutput
  print >> sys.stderr, "ACTUAL:"
  print >> sys.stderr, procstdout
  d=difflib.Differ()
  result = list(d.compare(procstdout.splitlines(1), expectedOutput.splitlines(1)))
  sys.stderr.writelines(result)
  OK=False

if ( procstderr!= expectedError ):
  print >> sys.stderr, "stderr not as expected"
  print >> sys.stderr, "EXPECTED:"
  print >> sys.stderr, expectedError
  print >> sys.stderr, "ACTUAL:"
  print >> sys.stderr, procstderr
  OK=False

if not OK:
  exit(1)
exit(0)
