#!/usr/bin/env python

import sys
import subprocess
import os


runProc = subprocess.Popen( [ "../src/saru-run-test","single", "fakeproject/passingtest.bash" ], stdout=subprocess.PIPE, stderr=subprocess.PIPE )
retcode = runProc.wait()

if( retcode != 0 ) :
  print >> sys.stderr, "returned non-zero exit code"
  exit(1)

(procstdout, procstderr) = runProc.communicate()

lines = procstderr.splitlines()
if ( len(lines)!= 0 ):
  print >> sys.stderr, "Non-empty stderr"
  print >> sys.stderr, procstderr
  exit(1)

lines = procstdout.splitlines()
if ( len(lines)!= 2 ):
  print >> sys.stderr, "Wrong number of stdout lines"
  print >> sys.stderr, procstdout
  exit(1)
expected = "passingtest.bash : OK\n1 / 1 [ 0 skipped ]"
if ( lines != expected.splitlines()):
  print >> sys.stderr, "Line of stdout not " + expected
  print >> sys.stderr, procstdout
  exit(1)
exit(0)
