#!/usr/bin/env python

import sys
import subprocess
import os


runProc = subprocess.Popen( [ "../src/saru-run-test","suite", "fakeproject/passingtest.bash" ], stdout=subprocess.PIPE, stderr=subprocess.PIPE )
retcode = runProc.wait()

if( retcode != 1 ) :
  print >> sys.stderr, "returned non-one exit code"
  exit(1)

(procstdout, procstderr) = runProc.communicate()

expectedStderr="saru-run-test : requires a directory name.\n"

if ( procstderr != expectedStderr ):
  print >> sys.stderr, "stderr not as expected"
  print >> sys.stderr, "EXPECTED:"
  print >> sys.stderr, expectedStderr
  print >> sys.stderr, "ACTUAL:"
  print >> sys.stderr, procstderr
  exit(1)
exit(0)

