#!/usr/bin/env python

import sys
import subprocess
import os


runProc = subprocess.Popen( [ "../src/saru-run-test","single", "fakeproject/testtag03.py" ], stdout=subprocess.PIPE, stderr=subprocess.PIPE )
retcode = runProc.wait()

if( retcode != 0 ) :
  print >> sys.stderr, "returned non-zero exit code"
  (procstdout, procstderr) = runProc.communicate()
  print >> sys.stderr, procstderr
  print >> sys.stderr, procstdout
  exit(1)

(procstdout, procstderr) = runProc.communicate()

expectedOutput="testtag03.py : OK\n"
expectedError=""

OK=True
if ( procstdout!= expectedOutput ):
  print >> sys.stderr, "output not as expected"
  print >> sys.stderr, "EXPECTED:"
  print >> sys.stderr, expectedOutput
  print >> sys.stderr, "ACTUAL:"
  print >> sys.stderr, procstdout
  OK=False

if ( procstderr!= expectedError ):
  print >> sys.stderr, "stderr not as expected"
  print >> sys.stderr, "EXPECTED:"
  print >> sys.stderr, expectedError
  print >> sys.stderr, "ACTUAL:"
  print >> sys.stderr, procstderr
  OK=False

if not OK:
  exit(1)
exit(0)
