#!/usr/bin/env python

# This test is to check that running saru on a cpp test will pick
# up any CxxInclude tags in the file.
#
# saru-run-test single needsinclude.cpp

import sys
import subprocess
import os
import shutil
import difflib

# Blow away any preexisting .saru directory.
if (os.path.isdir("fakeproject/.saru") ):
  shutil.rmtree("fakeproject/.saru")
if (os.path.isdir("fakeproject/.saru") ):
  print >> sys.stderr, "Unable to remove fakeprojet/.saru\n"
  exit(1)

# CD to the right place and run the tests.
origdir = os.getcwd()
os.chdir("fakeproject")

runProc = subprocess.Popen( [ "../../src/saru-run-test","single", "include" ], stdout=subprocess.PIPE, stderr=subprocess.PIPE )
(procstdout, procstderr) = runProc.communicate()

os.chdir(origdir)

expectedOutput="""include : FAILED
==MESSAGE==
saru-run-test : Doesn't run on a directory yet.


0 / 1 [ 0 skipped ]
"""


if ( runProc.returncode!=1 ):
  print "==FAILED==\n"
  print "STDOUT: \n"
  print procstdout
  print "STDERR: \n"
  print procstderr
  exit(1)

if(expectedOutput!=procstdout):
  print >> sys.stderr, "output not as expected"
  d=difflib.Differ()
  result = list(d.compare(procstdout.splitlines(1), expectedOutput.splitlines(1)))
  sys.stderr.writelines(result)
  exit(1)

exit(0)
