#!/usr/bin/env python

import sys
import subprocess
import os


searchProc = subprocess.Popen( [ "../src/saru-search", "tag", "testtag", "../fakeproject" ], stdout=subprocess.PIPE, stderr=subprocess.PIPE )
retcode = searchProc.wait()

if( retcode != 0 ) :
  exit(1)

com = searchProc.communicate()[0]
lines = com.splitlines()
if ( len(lines)!= 3 ):
  exit(1)
if ( lines[0] != "../fakeproject/testtag01.cpp" ):
  exit(1)
if ( lines[1] != "../fakeproject/testtag02.bash" ):
  exit(1)
if ( lines[1] != "../fakeproject/testtag03.py" ):
  exit(1)
exit(0)

