#!/usr/bin/env python

import sys;
import re;
import os

if ( len(sys.argv) != 2 ):
  print >> sys.stderr, "USAGE: saru-parse filename"
  exit(1)

if ( os.path.isdir(sys.argv[1]) ):
  print os.path.basename(sys.argv[0]) + " : Doesn't run on a directory yet."
  exit(1)

# How was this script run?
sarubinpath = os.path.dirname( os.path.abspath( sys.argv[0] ) )
fulltestname = sys.argv[1]
(testdir, testname) = os.path.split( fulltestname )


try:
  infile = open(fulltestname, "r")
except IOError:
  print >> sys.stderr, "saru-parse: Unable to open "+fulltestname
  exit(1)


pattern_directive = re.compile(r"^\s*//\s*TEST\s*:\s*(\S+)(.*)$")
pattern_comment = re.compile(r"^\s*//")
pattern_empty = re.compile(r"^\s*$")


print "File=\""+sys.argv[1]+"\""
for line in infile:
  if( pattern_empty.search(line) ) :
    continue
  match = pattern_directive.search(line); 
  if ( match ):
    print "   " + match.group(1) + " : \"" + match.group(2).strip() + "\"" 
    continue
  if ( pattern_comment.search(line) ):
    continue
  break

