#!/usr/bin/env python

print "// SARU:TestName Dummy Test"
print "// SARU:RequiresLibrary FakeDummy"
print "// SARU:RequiresLibrary FakeDummy"
print "// SARU:Tests That the tesing library works"
print "// SARU:Expected pass"
print "";
print "#include \"TestUtils.h\"";
print "";
print "void doTest()";
print "{";
print "  if(true)"
print "  {";
print "     Test::Fail(\"Unimplimented\");";
print "  }";
print "  Test::Ok();";
print "}";
