#!/usr/bin/env python


import sys;
import re;

if ( len(sys.argv) != 2 ):
  print >> sys.stderr, "USAGE: saru-parse filename"
  exit(1)

try:
  infile = open(sys.argv[1], "r")
except IOError:
  print >> sys.stderr, "saru-parse: Unable to open "+sys.argv[1]
  exit(1)


pattern_directive = re.compile(r"^\s*//\s*TEST\s*:\s*(\S+)(.*)$")
pattern_comment = re.compile(r"^\s*//")
pattern_empty = re.compile(r"^\s*$")


print "File=\""+sys.argv[1]+"\""
for line in infile:
  if( pattern_empty.search(line) ) :
    continue
  match = pattern_directive.search(line); 
  if ( match ):
    print "   " + match.group(1) + " : \"" + match.group(2).strip() + "\"" 
    continue
  if ( pattern_comment.search(line) ):
    continue
  break

