#!/usr/bin/env python

# Copyright (c) 2008, Michael Anderson
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the saru library nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY MICHAEL ANDERSON ''AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL MICHAEL ANDERSON BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import sys
import re
import subprocess
import os
import shutil

from stat import *





binname = os.path.basename( sys.argv[0] )

if ( len(sys.argv) != 4 ):
  print "USAGE: "+binname+" tag tagname directory"
  exit(1)

if( sys.argv[1] != "tag" ):
  print "USAGE: "+binname+" tag tagname directory"
  exit(1)

tagname = sys.argv[2]

dirname = sys.argv[3]

if ( not os.path.isdir( dirname ) ):
  print os.path.basename( sys.argv[0] )+" : only runs on a directories."
  exit(1)

# How was this script run?
sarubinpath = os.path.dirname( os.path.abspath( sys.argv[0] ) )
saruparse = os.path.normpath( sarubinpath + "/saru-parse" )

def fileHasSaruTag( filename, tag ):
  parseProcess = subprocess.Popen([ saruparse, "issaru", filename], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  retcode = parseProcess.wait()
  if(retcode!=0):
    errmesg = parseProcess.communicate()[1].strip();
    if(errmesg=="saru-parse : Unsuported file format for file saruconf"):
      return False
    print binname +" : saru-parse failed with error code " + repr(retcode)
    print errmesg
    exit(1)
  com = parseProcess.communicate()[0].strip()
  if((com=="NO") or (com=="UNKNOWN FORMAT")):
    return False;
  parseProcess = subprocess.Popen([ saruparse, "get", "Tag", filename], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  retcode = parseProcess.wait()
  if(retcode!=0):
    print binname +" : saru-parse failed with error code " + repr(retcode)
    errmesg = parseProcess.communicate()[1].strip();
    print errmesg
    exit(1)
  com = parseProcess.communicate()[0].strip()
  for l in com.split("\n"):
    if tag in l.split():
      return True

for root, dirs, files in os.walk(dirname):
  for file in files:
    filename = os.path.normpath( root + "/" + file )
    if fileHasSaruTag(filename,tagname):
      print filename
  if ".saru" in dirs:
   dirs.remove(".saru")
